version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # This prevents overwriting node_modules with the host directory
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: MySecureP@ss1
      DB_NAME: social_app
    command: npm start # Ensures the app starts correctly

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: MySecureP@ss1
      MYSQL_DATABASE: social_app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:

